site_name: ReadTheDocs Documentation

nav:
  - Introduction: 'index.md'
  - First steps: 'firstSteps.md'
  - Create Documentation: 'createDocumentation.md'
  - Navigation Menu: 'nav.md'
  - Upload Documentation: 'uploadDocumentation.md'

theme: readthedocs



